# -*- coding: utf-8 -*-
"""Data-Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7OxRFuCw1mvdCgUpLlcHy3OQdWFjAGF
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import csv
import xml.etree.ElementTree as ET

# Function to safely get text from an XML element
def get_text(element, tag):
    child = element.find(tag)
    return child.text if child is not None else ''

# Define the function to parse an XML file and extract data
def parse_xml_to_dict(xml_file):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    data = {
        'filename': get_text(root, 'filename'),
        'path': get_text(root, 'path'),
        'width': get_text(root.find('size'), 'width'),
        'height': get_text(root.find('size'), 'height'),
        'depth': get_text(root.find('size'), 'depth'),
    }

    objects = []
    for obj in root.findall('object'):
        obj_data = {
            'name': get_text(obj, 'name'),
            'pose': get_text(obj, 'pose'),
            'truncated': get_text(obj, 'truncated'),
            'difficult': get_text(obj, 'difficult'),
            'xmin': get_text(obj.find('bndbox'), 'xmin'),
            'ymin': get_text(obj.find('bndbox'), 'ymin'),
            'xmax': get_text(obj.find('bndbox'), 'xmax'),
            'ymax': get_text(obj.find('bndbox'), 'ymax'),
        }
        objects.append(obj_data)

    return data, objects

# Define the function to write the parsed data to CSV
def write_to_csv(csv_file, all_data):
    with open(csv_file, mode='w', newline='') as file:
        writer = csv.writer(file)
        # Write the headers
        writer.writerow(['filename', 'path', 'width', 'height', 'depth', 'object_name', 'pose', 'truncated', 'difficult', 'xmin', 'ymin', 'xmax', 'ymax'])

        # Write the data
        for data, objects in all_data:
            for obj in objects:
                writer.writerow([
                    data['filename'],
                    data['path'],
                    data['width'],
                    data['height'],
                    data['depth'],
                    obj['name'],
                    obj['pose'],
                    obj['truncated'],
                    obj['difficult'],
                    obj['xmin'],
                    obj['ymin'],
                    obj['xmax'],
                    obj['ymax']
                ])

# Directory containing the XML files
xml_directory = '/content/drive/MyDrive/Dataset/train'  # Change this to the directory where your XML files are stored

# List all XML files in the directory
xml_files = [os.path.join(xml_directory, f) for f in os.listdir(xml_directory) if f.endswith('.xml')]

# Collect data from all XML files
all_data = []
for xml_file in xml_files:
    try:
        data, objects = parse_xml_to_dict(xml_file)
        all_data.append((data, objects))
    except ET.ParseError as e:
        print(f"Error parsing {xml_file}: {e}")
    except Exception as e:
        print(f"Unexpected error with {xml_file}: {e}")

# Write the collected data to CSV
csv_file = '/content/drive/MyDrive/Dataset/train_annotations_all.csv'
write_to_csv(csv_file, all_data)

print("CSV file has been generated successfully.")